/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMaterialRouteImport } from './routes/app.material'
import { Route as AppMaterialsRouteImport } from './routes/app.materials'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppProcessingRouteImport } from './routes/app.processing'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppSessionRouteImport } from './routes/app.session'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'
import { Route as AppFlashcardsDocumentIdRouteImport } from './routes/app.flashcards.$documentId'
import { Route as AppQuestionsDocumentIdRouteImport } from './routes/app.questions.$documentId'
import { Route as AppSessionsIndexRouteImport } from './routes/app.sessions.index'
import { Route as AppSessionsSessionIdRouteImport } from './routes/app.sessions.$sessionId'
import { Route as AppSummaryDocumentIdRouteImport } from './routes/app.summary.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialRoute = AppMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingRoute = AppProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFlashcardsDocumentIdRoute = AppFlashcardsDocumentIdRouteImport.update({
  id: '/flashcards/$documentId',
  path: '/flashcards/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsDocumentIdRoute = AppQuestionsDocumentIdRouteImport.update({
  id: '/questions/$documentId',
  path: '/questions/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryDocumentIdRoute = AppSummaryDocumentIdRouteImport.update({
  id: '/summary/$documentId',
  path: '/summary/$documentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/material': typeof AppMaterialRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/plan': typeof AppPlanRoute
  '/app/processing': typeof AppProcessingRoute
  '/app/results': typeof AppResultsRoute
  '/app/session': typeof AppSessionRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/app/flashcards/$documentId': typeof AppFlashcardsDocumentIdRoute
  '/app/questions/$documentId': typeof AppQuestionsDocumentIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/summary/$documentId': typeof AppSummaryDocumentIdRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/material': typeof AppMaterialRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/plan': typeof AppPlanRoute
  '/app/processing': typeof AppProcessingRoute
  '/app/results': typeof AppResultsRoute
  '/app/session': typeof AppSessionRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/reset': typeof AuthResetRoute
  '/app': typeof AppIndexRoute
  '/app/flashcards/$documentId': typeof AppFlashcardsDocumentIdRoute
  '/app/questions/$documentId': typeof AppQuestionsDocumentIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/summary/$documentId': typeof AppSummaryDocumentIdRoute
  '/app/sessions': typeof AppSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/material': typeof AppMaterialRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/plan': typeof AppPlanRoute
  '/app/processing': typeof AppProcessingRoute
  '/app/results': typeof AppResultsRoute
  '/app/session': typeof AppSessionRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth_/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/app/flashcards/$documentId': typeof AppFlashcardsDocumentIdRoute
  '/app/questions/$documentId': typeof AppQuestionsDocumentIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/summary/$documentId': typeof AppSummaryDocumentIdRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/material'
    | '/app/materials'
    | '/app/plan'
    | '/app/processing'
    | '/app/results'
    | '/app/session'
    | '/app/settings'
    | '/auth/reset'
    | '/app/'
    | '/app/flashcards/$documentId'
    | '/app/questions/$documentId'
    | '/app/sessions/$sessionId'
    | '/app/summary/$documentId'
    | '/app/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/material'
    | '/app/materials'
    | '/app/plan'
    | '/app/processing'
    | '/app/results'
    | '/app/session'
    | '/app/settings'
    | '/auth/reset'
    | '/app'
    | '/app/flashcards/$documentId'
    | '/app/questions/$documentId'
    | '/app/sessions/$sessionId'
    | '/app/summary/$documentId'
    | '/app/sessions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/material'
    | '/app/materials'
    | '/app/plan'
    | '/app/processing'
    | '/app/results'
    | '/app/session'
    | '/app/settings'
    | '/auth_/reset'
    | '/app/'
    | '/app/flashcards/$documentId'
    | '/app/questions/$documentId'
    | '/app/sessions/$sessionId'
    | '/app/summary/$documentId'
    | '/app/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthResetRoute: typeof AuthResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/material': {
      id: '/app/material'
      path: '/material'
      fullPath: '/app/material'
      preLoaderRoute: typeof AppMaterialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processing': {
      id: '/app/processing'
      path: '/processing'
      fullPath: '/app/processing'
      preLoaderRoute: typeof AppProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/flashcards/$documentId': {
      id: '/app/flashcards/$documentId'
      path: '/flashcards/$documentId'
      fullPath: '/app/flashcards/$documentId'
      preLoaderRoute: typeof AppFlashcardsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions/$documentId': {
      id: '/app/questions/$documentId'
      path: '/questions/$documentId'
      fullPath: '/app/questions/$documentId'
      preLoaderRoute: typeof AppQuestionsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/': {
      id: '/app/sessions/'
      path: '/sessions'
      fullPath: '/app/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId': {
      id: '/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/summary/$documentId': {
      id: '/app/summary/$documentId'
      path: '/summary/$documentId'
      fullPath: '/app/summary/$documentId'
      preLoaderRoute: typeof AppSummaryDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMaterialRoute: typeof AppMaterialRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProcessingRoute: typeof AppProcessingRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSessionRoute: typeof AppSessionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFlashcardsDocumentIdRoute: typeof AppFlashcardsDocumentIdRoute
  AppQuestionsDocumentIdRoute: typeof AppQuestionsDocumentIdRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppSummaryDocumentIdRoute: typeof AppSummaryDocumentIdRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMaterialRoute: AppMaterialRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppPlanRoute: AppPlanRoute,
  AppProcessingRoute: AppProcessingRoute,
  AppResultsRoute: AppResultsRoute,
  AppSessionRoute: AppSessionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFlashcardsDocumentIdRoute: AppFlashcardsDocumentIdRoute,
  AppQuestionsDocumentIdRoute: AppQuestionsDocumentIdRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppSummaryDocumentIdRoute: AppSummaryDocumentIdRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthResetRoute: AuthResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
